#pragma once

#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP6
#define I2C1_SCL_PIN GP7

#define OLED_BRIGHTNESS 90
#define OLED_TIMEOUT 5000
#define OLED_UPDATE_INTERVAL 100
#define OLED_DISPLAY_ADDRESS 0x3C
#define OLED_BOOT_TIMEOUT 100
